### ISSUE TITLE
Issue with tutorial 3 and 4

### ISSUE THREAD

**Issue by anicolson** [pronobis/libspn#92]
Hi, I have been able to get tutorials 1a-1c, 2, and 6 to work fine. However, when trying to get tutorial 3 and 4 to work, the following error occurs:

---
[WARNING] [tensorflow:__getattr__] From tutorial_4.py:50: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

[WARNING] [tensorflow:__getattr__] From /home/aaron/tf/lib/python3.6/site-packages/libspn/graph/node.py:40: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

[WARNING] [tensorflow:__getattr__] From /home/aaron/tf/lib/python3.6/site-packages/libspn/graph/leaf/indicator.py:63: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

[WARNING] [tensorflow:__getattr__] From /home/aaron/tf/lib/python3.6/site-packages/libspn/graph/leaf/indicator.py:91: The name tf.log is deprecated. Please use tf.math.log instead.

Traceback (most recent call last):
  File "tutorial_4.py", line 71, in <module>
    root_log_prob = root.get_log_value(inference_type=inference_type)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/graph/node.py", line 385, in get_log_value
    return LogValue(inference_type).get_value(self)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/inference/value.py", line 65, in get_value
    return compute_graph_up(root, val_fun=fun, all_values=self._values)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/graph/algorithms.py", line 61, in compute_graph_up
    last_val = val_fun(next_node, *input_vals)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/inference/value.py", line 59, in fun
    return node._compute_log_value(*args, **kwargs)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/utils/lrucache.py", line 71, in helper
    memo[key] = f(*args, **kwargs)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/graph/op/products_layer.py", line 251, in _compute_log_value
    values = self._compute_value_common(*value_tensors, padding_value=0.0)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/utils/lrucache.py", line 71, in helper
    memo[key] = f(*args, **kwargs)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/graph/op/products_layer.py", line 242, in _compute_value_common
    pad_elem=padding_value)
  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/utils/math.py", line 186, in gather_cols_3d
    pad_elem = np.array(pad_elem).astype(tf.DType(params.dtype).as_numpy_dtype)
  File "/home/aaron/tf/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 80, in __init__
    type_enum = int(type_enum)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'DType'
---

It seems to be related with the following lines:

hard_em_learning = spn.HardEMLearning(root=root)
update_op = hard_em_learning.accumulate_and_update_weights()
llh_op = tf.reduce_mean(root.get_log_value())

and something going on here:

  File "/home/aaron/tf/lib/python3.6/site-packages/libspn/utils/math.py", line 186, in gather_cols_3d
    pad_elem = np.array(pad_elem).astype(tf.DType(params.dtype).as_numpy_dtype)
  File "/home/aaron/tf/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py", line 80, in __init__
    type_enum = int(type_enum)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'DType'

Is there a package that I don't have that would cause this?

I am running tensorflow 1.14, and tensorflow_probability 0.7.0/

 I have not tried tutorial 5.

**Comment by anicolson** [comment]
Would appreciate a response
