### ISSUE TITLE
Wicker SPN Tutorial not working

### ISSUE THREAD

**Issue by steven-lang** [pronobis/libspn#93]
The tutorial about [Wicker SPNs](https://www.libspn.org/tutorials/tutorial_7_mnist_continuous_gd_wicker.html) is not working. On execution, I get:
```
Testing:   0%|                                                                                                                                                                              | 0/313 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
	 [[{{node LogValue_1/ConvProductsDepthwise/Conv2D}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/benchmarks/performance.py", line 417, in <module>
    result = run()
  File "python/benchmarks/performance.py", line 131, in run_wicker_spn
    batch_matches = sess.run(match_op, fd(batch_x, batch_y))
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
	 [[node LogValue_1/ConvProductsDepthwise/Conv2D (defined at /home/steven/test/env/lib/python3.6/site-packages/libspn/graph/op/conv_products_depthwise.py:64) ]]

Errors may have originated from an input operation.
Input Source operations connected to node LogValue_1/ConvProductsDepthwise/Conv2D:
 LogValue_1/ConvProductsDepthwise/ones (defined at /home/steven/test/env/lib/python3.6/site-packages/libspn/graph/op/conv_products_depthwise.py:60)	
 LogValue_1/ConvProductsDepthwise/Reshape_1 (defined at /home/steven/test/env/lib/python3.6/site-packages/libspn/graph/op/conv_products_depthwise.py:72)

Original stack trace for 'LogValue_1/ConvProductsDepthwise/Conv2D':
  File "python/benchmarks/performance.py", line 417, in <module>
    result = run()
  File "python/benchmarks/performance.py", line 113, in run_wicker_spn
    predictions, = mpe_state.get_state(root_marginalized, marginalized_ivs)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/inference/mpe_state.py", line 45, in get_state
    self._mpe_path.get_mpe_path(root)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/inference/mpe_path.py", line 72, in get_mpe_path
    self._value.get_value(root)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/inference/value.py", line 65, in get_value
    return compute_graph_up(root, val_fun=fun, all_values=self._values)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/graph/algorithms.py", line 61, in compute_graph_up
    last_val = val_fun(next_node, *input_vals)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/inference/value.py", line 59, in fun
    return node._compute_log_value(*args, **kwargs)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/utils/lrucache.py", line 71, in helper
    memo[key] = f(*args, **kwargs)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/graph/op/conv_products_depthwise.py", line 64, in _compute_log_value
    data_format='NCHW'
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by jostosh** [comment]
Hi Steven, thanks for your interest in the library. I was wondering, are you running on CPU or GPU? For some ops that are used the CPU implementation isn't available, so that could be the source of the issue. Also, which TF version are you using?

**Comment by steven-lang** [comment]
Hi, thanks for the quick response and sorry for not specifying further information in the first place!

I've run this on both, CPU and GPU, with the same result.

The tensorflow version is `1.14.0`.

**Comment by jostosh** [comment]
Fixed and incremented `libspn` version to 0.1.3. Thanks for pointing it out!

**Comment by steven-lang** [comment]
Great, thanks for the quick fix, it's working now!

**Comment by steven-lang** [comment]
That was too early. I ran into the next issue now, still simply the tutorial code:

```
Testing: 100%|███████████████████████████████████████████| 313/313 [00:23<00:00, 13.49it/s, Accuracy=0.00]
Before training test accuracy = 0.09
Training:   0%|                                                                  | 0/1875 [00:00<?, ?it/s]2020-01-16 12:58:48.511616: E tensorflow/core/common_runtime/executor.cc:641] Executor failed to create kernel. Invalid argument: Current libxsmm and customized CPU implementations do not yet support dilation rates larger than 1.
	 [[{{node LearnGD/ParameterUpdate/gradients/LogValue/ConvProductsDepthwise_4/Conv2D_grad/Conv2DBackpropInput}}]]
Traceback (most recent call last):
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Current libxsmm and customized CPU implementations do not yet support dilation rates larger than 1.
	 [[{{node LearnGD/ParameterUpdate/gradients/LogValue/ConvProductsDepthwise_4/Conv2D_grad/Conv2DBackpropInput}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/benchmarks/performance.py", line 417, in <module>
    result = run()
  File "python/benchmarks/performance.py", line 143, in run_wicker_spn
    [match_op, gd_update_op], fd(batch_x, batch_y))
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Current libxsmm and customized CPU implementations do not yet support dilation rates larger than 1.
	 [[node LearnGD/ParameterUpdate/gradients/LogValue/ConvProductsDepthwise_4/Conv2D_grad/Conv2DBackpropInput (defined at /home/steven/test/env/lib/python3.6/site-packages/libspn/learning/gd.py:108) ]]

Errors may have originated from an input operation.
Input Source operations connected to node LearnGD/ParameterUpdate/gradients/LogValue/ConvProductsDepthwise_4/Conv2D_grad/Conv2DBackpropInput:
 LogValue/ConvProductsDepthwise_4/ones (defined at /home/steven/test/env/lib/python3.6/site-packages/libspn/graph/op/conv_products_depthwise.py:60)

Original stack trace for 'LearnGD/ParameterUpdate/gradients/LogValue/ConvProductsDepthwise_4/Conv2D_grad/Conv2DBackpropInput':
  File "python/benchmarks/performance.py", line 417, in <module>
    result = run()
  File "python/benchmarks/performance.py", line 106, in run_wicker_spn
    gd_update_op = gd_learning.learn(optimizer=optimizer, post_gradient_ops=True)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/learning/gd.py", line 108, in learn
    minimize = optimizer.minimize(loss=loss)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 403, in minimize
    grad_loss=grad_loss)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 403, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/nn_grad.py", line 596, in _Conv2DGrad
    data_format=data_format),
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1407, in conv2d_backprop_input
    name=name)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'LogValue/ConvProductsDepthwise_4/Conv2D', defined at:
  File "python/benchmarks/performance.py", line 417, in <module>
    result = run()
  File "python/benchmarks/performance.py", line 97, in run_wicker_spn
    root_log_prob = root.get_log_value(inference_type=inference_type)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/graph/node.py", line 385, in get_log_value
    return LogValue(inference_type).get_value(self)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/inference/value.py", line 65, in get_value
    return compute_graph_up(root, val_fun=fun, all_values=self._values)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/graph/algorithms.py", line 61, in compute_graph_up
    last_val = val_fun(next_node, *input_vals)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/inference/value.py", line 59, in fun
    return node._compute_log_value(*args, **kwargs)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/utils/lrucache.py", line 71, in helper
    memo[key] = f(*args, **kwargs)
  File "/home/steven/test/env/lib/python3.6/site-packages/libspn/graph/op/conv_products_depthwise.py", line 64, in _compute_log_value
    data_format='NHWC'
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/steven/test/env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Exception ignored in: <bound method tqdm.__del__ of Training:   0%|                                                                  | 0/1875 [00:00<?, ?it/s]>
Traceback (most recent call last):
  File "/home/steven/test/env/lib/python3.6/site-packages/tqdm/std.py", line 1039, in __del__
  File "/home/steven/test/env/lib/python3.6/site-packages/tqdm/std.py", line 1223, in close
  File "/home/steven/test/env/lib/python3.6/site-packages/tqdm/std.py", line 555, in _decr_instances
  File "/home/steven/test/env/lib/python3.6/site-packages/tqdm/_monitor.py", line 51, in exit
  File "/usr/lib/python3.6/threading.py", line 521, in set
  File "/usr/lib/python3.6/threading.py", line 364, in notify_all
  File "/usr/lib/python3.6/threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
```

**Comment by jostosh** [comment]
This is related to the fact that some of the Ops that are used do not have a CPU implementation in the TensorFlow backend:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Current libxsmm and customized CPU implementations do not yet support dilation rates larger than 1.
	 [[node LearnGD/ParameterUpdate/gradients/LogValue/ConvProductsDepthwise_4/Conv2D_grad/Conv2DBackpropInput (defined at /home/steven/test/env/lib/python3.6/site-packages/libspn/learning/gd.py:108) ]]

```

**Comment by steven-lang** [comment]
Ah sorry, I was quite sure that I ran the code with GPU support but it appears that in between all these TensorFlow logs, Cuda initialization has failed due to the wrong driver:

```
...
2020-02-01 14:15:44.685420: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-02-01 14:15:44.685428: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-02-01 14:15:44.685435: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2020-02-01 14:15:44.685443: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2020-02-01 14:15:44.685450: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2020-02-01 14:15:44.685456: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2020-02-01 14:15:44.685463: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7

...

2020-02-01 14:15:45.207000: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-02-01 14:15:45.207210: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-02-01 14:15:45.207241: E tensorflow/stream_executor/cuda/cuda_dnn.cc:337] Possibly insufficient driver version: 430.50.0
...
```

I only saw all the `Successfully opened dynamic library libcXYZ.so.10.0` messages and assumed that Cuda was working.

The issue at hand: LibSPN needs `tensorflow==1.14.0` which only supports up to Cuda `10.0` which needs the cuDNN driver version `410.48` (see [here](https://docs.nvidia.com/deeplearning/sdk/cudnn-support-matrix/index.html)). At the time I had cuDNN version `430.50.0` installed (which seems to not appear in the driver support matrix). Upgrading to the latest `440.18` driver solved the issue though.

Sorry for the confusion!
